export const GET_SNEAKERS = "GET_SNEAKERS"
export const GET_SNEAKERS_SUCCESS = "GET_SNEAKERS_SUCCESS"
export const GET_SNEAKERS_FAILURE = "GET_SNEAKERS_FAILURE"


export const GET_SNEAKER_DETAILS = "GET_SNEAKER_DETAILS"
export const GET_SNEAKER_DETAILS_SUCCESS = "GET_SNEAKER_DETAILS_SUCCESS"
export const GET_SNEAKER_DETAILS_FAILURE = "GET_SNEAKER_DETAILS_FAILURE"
export const GET_SNEAKER_DETAILS_RESET = "GET_SNEAKER_DETAILS_RESET"
